name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - uses: actions/checkout@v4

      # 2. Criar diretório dist caso não exista
      - name: Criar diretório dist
        run: |
          mkdir -p dist

      # 3. Gerar uma animação simples de cobrinha
      - name: Gerar animação de cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # A animação será salva em dist/snake.svg
          outputs: dist/snake.svg

      # 4. Commit e push do arquivo gerado
      - name: Commit e push da animação
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/snake.svg
          git commit -m "Gerando nova animação com o GitHub Actions" || echo "Nenhuma mudança para commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
