name: Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Roda todo dia à meia-noite (UTC)
  workflow_dispatch: # Permite rodar manualmente o workflow

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake.svg

      - name: Publicar no repositório
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist
